all:
	clang++-3.5 -O3  -I /home/murillo/git/simpleMPM/simpleMPM/src/eigen simpleMPM.cpp   -o MPMrun

debug:
	clang++-3.5 -O0 -g -I /home/murillo/git/simpleMPM/simpleMPM/src/eigen simpleMPM.cpp -o MPMdbg
